# Generated by Django 3.0.6 on 2020-07-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('focus', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('difficulty', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
