# Generated by Django 3.0.6 on 2020-07-03 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('body_part', models.CharField(choices=[('C', 'Chest'), ('B', 'Back'), ('S', 'Shoulders'), ('A', 'Arms'), ('L', 'Legs'), ('O', 'Cardio')], max_length=1)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Workout')),
            ],
        ),
    ]
